
INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Davines", "Replumping Shampoo", "For delicate hair prone to breakage. Luxuriously creamy and sudsy, Replumping Shampoo moisturizes, protects and enhances the elasticity of hair.", "8.45 fl.oz.", 28.00, 10, 5.99, "test1", "../assets/images/products/davines_replumpingshampoo_900x900.jpg", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Kevin Murphy", "POWDER.PUFF", "An instant poof in a jar! To create a messy casual volume, gently tap a few shakes on the hair that you want body on, and the powder morphs into a product that holds.", ".50oz.", 29.99, 10, 5.99, "test1", "../assets/images/products/KMurphy_POWDER.PUFF.jpg", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Davines", "Nourishing Vegetarian Miracle Conditioner", "For hair in serious need of repair. Deeply moisturizing and healing, Vegetarian Miracle is an intensive conditioner that replenishes the hydration levels of brittle hair leaving it stronger and more resilient.", "8.77 oz.", 34.00, 10, 5.99, "test1", "../assets/images/products/davines_conditioner.jpeg", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Kevin Murphy", "YOUNG.AGAIN.WASH", "A restorative shampoo containing a complex of Amino Acids. Anti-ageing extracts from Lotus flower and Orchid help to renew youthful lustre and shine to dry brittle hair.", "8.4 fl.oz.", 29.99, 10, 5.99, "test1", "../assets/images/products/KMurphy_YOUNG.AGAIN_.WASH_.jpg", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Eleven", "I WANT BODY VOLUME SHAMPOO", "A lightweight shampoo that creates body, volume and shine. With hydrolysed wheat and soy protein to provide thicker, fuller hair, I Want Body Volume Shampoo is perfect for fine hair or anyone wanting a volume boost.", "10.3 fl.oz.", 23.95, 10, 5.99, "test1", "../assets/images/products/eleven_shampoo166x288.png", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Zenagen", "Revolve Treatment for Women", "Zenagen Revolve Treatment for Women is a non daily, luxurious, naturally derived hair loss treatment system specifically tailored for female hair loss, thinning, and shedding. 1 bottle of the shampoo based Zenagen Revolve Treatment for Women will last 3 months, and results can start to be seen as early as 4 weeks after using the product consistently.", "6 fl.oz.", 79.99, 10, 5.99, "test1", "../assets/images/products/Zen_Revolve198x300.png", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Eleven", "3 MINUTE REPAIR RINSE OUT TREATMENT", "A protein & moisture blend to strengthen and nourish dry, damaged hair. The blend of shea butter and hydrolysed wheat proteins treat while repairing hair.", "6.8 oz.", 26.95, 10, 5.99, "test1", "../assets/images/products/eleven_rinse.png", now(), now());

INSERT INTO products (brand, name, description, size, price, stock_quantity, cost, vendor, photo, createdAt, updatedAt) VALUES("Zenagen", "Zenagen Revolve Hair Loss Conditioner (Unisex)", "The second step in the Zenagen Revolve system, Zenagen Revolve Conditioner is a unisex product designed to complement the Revolve Treatments for men and women to reduce shedding, increase hair density and volume while maximizing shine and manageability. Conditioning is recommended after each Zenagen Revolve Treatment application.", "5 fl.oz.", 49.99, 10, 5.99, "test4", "../assets/images/products/zen_cond.jpg", now(), now());


SELECT * FROM products;

